#!/bin/bash
#
src="src"
modules=$(find $src/ -mindepth 1 -maxdepth 1 -type d)
initDir=$(pwd)

mkdir -p $initDir/lib
mkdir -p $initDir/bin
mkdir -p $initDir/include

for module in $modules; do
  module=$(basename $module)
  # if the .built file is not present skip the module
  if [ ! -f $src/$module/.built ]; then
    echo "Skipping $module..."
    continue
  else
    echo "Installing $module..."
  fi
  cd $src/$module
  if [ -d "bin" ]; then
    cp bin/* $initDir/bin
  fi
  if [ -d "include" ]; then
    cp include/* $initDir/include
  fi

  cp *.h $initDir/include
  cd $initDir
  echo "Creating lib$module cmesa.a..."
  ar rcs lib/lib$module\cmesa.a bin/*$module*.o
done
