!------------------------------------------------------------------------------
!  module interface_def
!  This module contains libmesac/chem data structure definitions which are
!  built to be compatible with those in mesa/chem/chem_def.f90 while also
!  being compatible with C datatyps. This module also contains subroutines to convert
!  between the two data structures.
!------------------------------------------------------------------------------
module chem_interface_def

  use iso_c_binding, only: c_int, c_double, c_bool, c_char, c_ptr, c_f_pointer
  use chem_def

  !------------------------------------------------------------------------------
  !  Type definitions
  !------------------------------------------------------------------------------

  !------------------------------------------------------------------------------
  !  c_Chem_Ids
  !  This type is a C-compatible version of the Chem_Ids type in mesa/chem/chem_def.f90
  !------------------------------------------------------------------------------
  type, bind(C) :: c_Chem_Ids
    integer(c_int) :: ih1
    integer(c_int) :: ih2
    integer(c_int) :: ih3
    integer(c_int) :: ihe3
    integer(c_int) :: ihe4
    integer(c_int) :: ili6
    integer(c_int) :: ili7
    integer(c_int) :: ili8
    integer(c_int) :: ibe7
    integer(c_int) :: ibe8
    integer(c_int) :: ibe9
    integer(c_int) :: ibe10
    integer(c_int) :: ibe11
    integer(c_int) :: ib8
    integer(c_int) :: ib10
    integer(c_int) :: ib11
    integer(c_int) :: ib12
    integer(c_int) :: ib13
    integer(c_int) :: ib14
    integer(c_int) :: ic9
    integer(c_int) :: ic10
    integer(c_int) :: ic11
    integer(c_int) :: ic12
    integer(c_int) :: ic13
    integer(c_int) :: ic14
    integer(c_int) :: ic15
    integer(c_int) :: ic16
    integer(c_int) :: in12
    integer(c_int) :: in13
    integer(c_int) :: in14
    integer(c_int) :: in15
    integer(c_int) :: in16
    integer(c_int) :: in17
    integer(c_int) :: in18
    integer(c_int) :: in19
    integer(c_int) :: in20
    integer(c_int) :: io13
    integer(c_int) :: io14
    integer(c_int) :: io15
    integer(c_int) :: io16
    integer(c_int) :: io17
    integer(c_int) :: io18
    integer(c_int) :: io19
    integer(c_int) :: io20
    integer(c_int) :: if15
    integer(c_int) :: if16
    integer(c_int) :: if17
    integer(c_int) :: if18
    integer(c_int) :: if19
    integer(c_int) :: if20
    integer(c_int) :: if21
    integer(c_int) :: if22
    integer(c_int) :: if23
    integer(c_int) :: if24
    integer(c_int) :: ine17
    integer(c_int) :: ine18
    integer(c_int) :: ine19
    integer(c_int) :: ine20
    integer(c_int) :: ine21
    integer(c_int) :: ine22
    integer(c_int) :: ine23
    integer(c_int) :: ine24
    integer(c_int) :: ine25
    integer(c_int) :: ine26
    integer(c_int) :: ine27
    integer(c_int) :: ine28
    integer(c_int) :: ina20
    integer(c_int) :: ina21
    integer(c_int) :: ina22
    integer(c_int) :: ina23
    integer(c_int) :: ina24
    integer(c_int) :: ina25
    integer(c_int) :: ina26
    integer(c_int) :: ina27
    integer(c_int) :: ina28
    integer(c_int) :: ina29
    integer(c_int) :: ina30
    integer(c_int) :: ina31
    integer(c_int) :: img20
    integer(c_int) :: img21
    integer(c_int) :: img22
    integer(c_int) :: img23
    integer(c_int) :: img24
    integer(c_int) :: img25
    integer(c_int) :: img26
    integer(c_int) :: img27
    integer(c_int) :: img28
    integer(c_int) :: img29
    integer(c_int) :: img30
    integer(c_int) :: img31
    integer(c_int) :: img32
    integer(c_int) :: img33
    integer(c_int) :: ial22
    integer(c_int) :: ial23
    integer(c_int) :: ial24
    integer(c_int) :: ial25
    integer(c_int) :: ial26
    integer(c_int) :: ial27
    integer(c_int) :: ial28
    integer(c_int) :: ial29
    integer(c_int) :: ial30
    integer(c_int) :: ial31
    integer(c_int) :: ial32
    integer(c_int) :: ial33
    integer(c_int) :: ial34
    integer(c_int) :: ial35
    integer(c_int) :: isi22
    integer(c_int) :: isi23
    integer(c_int) :: isi24
    integer(c_int) :: isi25
    integer(c_int) :: isi26
    integer(c_int) :: isi27
    integer(c_int) :: isi28
    integer(c_int) :: isi29
    integer(c_int) :: isi30
    integer(c_int) :: isi31
    integer(c_int) :: isi32
    integer(c_int) :: isi33
    integer(c_int) :: isi34
    integer(c_int) :: isi35
    integer(c_int) :: isi36
    integer(c_int) :: isi37
    integer(c_int) :: isi38
    integer(c_int) :: ip26
    integer(c_int) :: ip27
    integer(c_int) :: ip28
    integer(c_int) :: ip29
    integer(c_int) :: ip30
    integer(c_int) :: ip31
    integer(c_int) :: ip32
    integer(c_int) :: ip33
    integer(c_int) :: ip34
    integer(c_int) :: ip35
    integer(c_int) :: ip36
    integer(c_int) :: ip37
    integer(c_int) :: ip38
    integer(c_int) :: ip39
    integer(c_int) :: ip40
    integer(c_int) :: is27
    integer(c_int) :: is28
    integer(c_int) :: is29
    integer(c_int) :: is30
    integer(c_int) :: is31
    integer(c_int) :: is32
    integer(c_int) :: is33
    integer(c_int) :: is34
    integer(c_int) :: is35
    integer(c_int) :: is36
    integer(c_int) :: is37
    integer(c_int) :: is38
    integer(c_int) :: is39
    integer(c_int) :: is40
    integer(c_int) :: is41
    integer(c_int) :: is42
    integer(c_int) :: icl31
    integer(c_int) :: icl32
    integer(c_int) :: icl33
    integer(c_int) :: icl34
    integer(c_int) :: icl35
    integer(c_int) :: icl36
    integer(c_int) :: icl37
    integer(c_int) :: icl38
    integer(c_int) :: icl39
    integer(c_int) :: icl40
    integer(c_int) :: icl41
    integer(c_int) :: icl42
    integer(c_int) :: icl43
    integer(c_int) :: icl44
    integer(c_int) :: iar31
    integer(c_int) :: iar32
    integer(c_int) :: iar33
    integer(c_int) :: iar34
    integer(c_int) :: iar35
    integer(c_int) :: iar36
    integer(c_int) :: iar37
    integer(c_int) :: iar38
    integer(c_int) :: iar39
    integer(c_int) :: iar40
    integer(c_int) :: iar41
    integer(c_int) :: iar42
    integer(c_int) :: iar43
    integer(c_int) :: iar44
    integer(c_int) :: iar45
    integer(c_int) :: iar46
    integer(c_int) :: iar47
    integer(c_int) :: ik35
    integer(c_int) :: ik36
    integer(c_int) :: ik37
    integer(c_int) :: ik38
    integer(c_int) :: ik39
    integer(c_int) :: ik40
    integer(c_int) :: ik41
    integer(c_int) :: ik42
    integer(c_int) :: ik43
    integer(c_int) :: ik44
    integer(c_int) :: ik45
    integer(c_int) :: ik46
    integer(c_int) :: ik47
    integer(c_int) :: ica35
    integer(c_int) :: ica36
    integer(c_int) :: ica37
    integer(c_int) :: ica38
    integer(c_int) :: ica39
    integer(c_int) :: ica40
    integer(c_int) :: ica41
    integer(c_int) :: ica42
    integer(c_int) :: ica43
    integer(c_int) :: ica44
    integer(c_int) :: ica45
    integer(c_int) :: ica46
    integer(c_int) :: ica47
    integer(c_int) :: ica48
    integer(c_int) :: ica49
    integer(c_int) :: ica50
    integer(c_int) :: ica51
    integer(c_int) :: ica52
    integer(c_int) :: ica53
    integer(c_int) :: isc40
    integer(c_int) :: isc41
    integer(c_int) :: isc42
    integer(c_int) :: isc43
    integer(c_int) :: isc44
    integer(c_int) :: isc45
    integer(c_int) :: isc46
    integer(c_int) :: isc47
    integer(c_int) :: isc48
    integer(c_int) :: isc49
    integer(c_int) :: isc50
    integer(c_int) :: isc51
    integer(c_int) :: isc52
    integer(c_int) :: isc53
    integer(c_int) :: iti39
    integer(c_int) :: iti40
    integer(c_int) :: iti41
    integer(c_int) :: iti42
    integer(c_int) :: iti43
    integer(c_int) :: iti44
    integer(c_int) :: iti45
    integer(c_int) :: iti46
    integer(c_int) :: iti47
    integer(c_int) :: iti48
    integer(c_int) :: iti49
    integer(c_int) :: iti50
    integer(c_int) :: iti51
    integer(c_int) :: iti52
    integer(c_int) :: iti53
    integer(c_int) :: iti54
    integer(c_int) :: iti55
    integer(c_int) :: iv43
    integer(c_int) :: iv44
    integer(c_int) :: iv45
    integer(c_int) :: iv46
    integer(c_int) :: iv47
    integer(c_int) :: iv48
    integer(c_int) :: iv49
    integer(c_int) :: iv50
    integer(c_int) :: iv51
    integer(c_int) :: iv52
    integer(c_int) :: iv53
    integer(c_int) :: iv54
    integer(c_int) :: iv55
    integer(c_int) :: iv56
    integer(c_int) :: iv57
    integer(c_int) :: icr43
    integer(c_int) :: icr44
    integer(c_int) :: icr45
    integer(c_int) :: icr46
    integer(c_int) :: icr47
    integer(c_int) :: icr48
    integer(c_int) :: icr49
    integer(c_int) :: icr50
    integer(c_int) :: icr51
    integer(c_int) :: icr52
    integer(c_int) :: icr53
    integer(c_int) :: icr54
    integer(c_int) :: icr55
    integer(c_int) :: icr56
    integer(c_int) :: icr57
    integer(c_int) :: icr58
    integer(c_int) :: icr59
    integer(c_int) :: icr60
    integer(c_int) :: icr61
    integer(c_int) :: icr62
    integer(c_int) :: icr63
    integer(c_int) :: icr64
    integer(c_int) :: icr65
    integer(c_int) :: icr66
    integer(c_int) :: imn46
    integer(c_int) :: imn47
    integer(c_int) :: imn48
    integer(c_int) :: imn49
    integer(c_int) :: imn50
    integer(c_int) :: imn51
    integer(c_int) :: imn52
    integer(c_int) :: imn53
    integer(c_int) :: imn54
    integer(c_int) :: imn55
    integer(c_int) :: imn56
    integer(c_int) :: imn57
    integer(c_int) :: imn58
    integer(c_int) :: imn59
    integer(c_int) :: imn60
    integer(c_int) :: imn61
    integer(c_int) :: imn62
    integer(c_int) :: imn63
    integer(c_int) :: ife46
    integer(c_int) :: ife47
    integer(c_int) :: ife48
    integer(c_int) :: ife49
    integer(c_int) :: ife50
    integer(c_int) :: ife51
    integer(c_int) :: ife52
    integer(c_int) :: ife53
    integer(c_int) :: ife54
    integer(c_int) :: ife55
    integer(c_int) :: ife56
    integer(c_int) :: ife57
    integer(c_int) :: ife58
    integer(c_int) :: ife59
    integer(c_int) :: ife60
    integer(c_int) :: ife61
    integer(c_int) :: ife62
    integer(c_int) :: ife63
    integer(c_int) :: ife64
    integer(c_int) :: ife65
    integer(c_int) :: ife66
    integer(c_int) :: ife68
    integer(c_int) :: ico50
    integer(c_int) :: ico51
    integer(c_int) :: ico52
    integer(c_int) :: ico53
    integer(c_int) :: ico54
    integer(c_int) :: ico55
    integer(c_int) :: ico56
    integer(c_int) :: ico57
    integer(c_int) :: ico58
    integer(c_int) :: ico59
    integer(c_int) :: ico60
    integer(c_int) :: ico61
    integer(c_int) :: ico62
    integer(c_int) :: ico63
    integer(c_int) :: ico64
    integer(c_int) :: ico65
    integer(c_int) :: ico66
    integer(c_int) :: ico67
    integer(c_int) :: ini50
    integer(c_int) :: ini51
    integer(c_int) :: ini52
    integer(c_int) :: ini53
    integer(c_int) :: ini54
    integer(c_int) :: ini55
    integer(c_int) :: ini56
    integer(c_int) :: ini57
    integer(c_int) :: ini58
    integer(c_int) :: ini59
    integer(c_int) :: ini60
    integer(c_int) :: ini61
    integer(c_int) :: ini62
    integer(c_int) :: ini63
    integer(c_int) :: ini64
    integer(c_int) :: ini65
    integer(c_int) :: ini66
    integer(c_int) :: ini67
    integer(c_int) :: ini68
    integer(c_int) :: ini69
    integer(c_int) :: ini70
    integer(c_int) :: ini71
    integer(c_int) :: ini72
    integer(c_int) :: ini73
    integer(c_int) :: icu56
    integer(c_int) :: icu57
    integer(c_int) :: icu58
    integer(c_int) :: icu59
    integer(c_int) :: icu60
    integer(c_int) :: icu61
    integer(c_int) :: icu62
    integer(c_int) :: icu63
    integer(c_int) :: icu64
    integer(c_int) :: icu65
    integer(c_int) :: icu66
    integer(c_int) :: icu67
    integer(c_int) :: icu68
    integer(c_int) :: icu69
    integer(c_int) :: icu70
    integer(c_int) :: icu71
    integer(c_int) :: icu72
    integer(c_int) :: izn55
    integer(c_int) :: izn56
    integer(c_int) :: izn57
    integer(c_int) :: izn58
    integer(c_int) :: izn59
    integer(c_int) :: izn60
    integer(c_int) :: izn61
    integer(c_int) :: izn62
    integer(c_int) :: izn63
    integer(c_int) :: izn64
    integer(c_int) :: izn65
    integer(c_int) :: izn66
    integer(c_int) :: izn67
    integer(c_int) :: izn68
    integer(c_int) :: izn69
    integer(c_int) :: izn70
    integer(c_int) :: izn71
    integer(c_int) :: izn72
    integer(c_int) :: izn73
    integer(c_int) :: izn74
    integer(c_int) :: iga60
    integer(c_int) :: iga61
    integer(c_int) :: iga62
    integer(c_int) :: iga63
    integer(c_int) :: iga64
    integer(c_int) :: iga65
    integer(c_int) :: iga66
    integer(c_int) :: iga67
    integer(c_int) :: iga68
    integer(c_int) :: iga69
    integer(c_int) :: iga70
    integer(c_int) :: iga71
    integer(c_int) :: iga72
    integer(c_int) :: iga73
    integer(c_int) :: iga74
    integer(c_int) :: iga75
    integer(c_int) :: ige59
    integer(c_int) :: ige60
    integer(c_int) :: ige61
    integer(c_int) :: ige62
    integer(c_int) :: ige63
    integer(c_int) :: ige64
    integer(c_int) :: ige65
    integer(c_int) :: ige66
    integer(c_int) :: ige67
    integer(c_int) :: ige68
    integer(c_int) :: ige69
    integer(c_int) :: ige70
    integer(c_int) :: ige71
    integer(c_int) :: ige72
    integer(c_int) :: ige73
    integer(c_int) :: ige74
    integer(c_int) :: ige75
    integer(c_int) :: ige76
    integer(c_int) :: ias71
    integer(c_int) :: ias72
    integer(c_int) :: ias73
    integer(c_int) :: ias74
    integer(c_int) :: ias75
    integer(c_int) :: ias76
    integer(c_int) :: ias77
    integer(c_int) :: ias78
    integer(c_int) :: ias79
    integer(c_int) :: ise68
    integer(c_int) :: ise69
    integer(c_int) :: ise70
    integer(c_int) :: ise71
    integer(c_int) :: ise72
    integer(c_int) :: ise73
    integer(c_int) :: ise74
    integer(c_int) :: ise75
    integer(c_int) :: ise76
    integer(c_int) :: ikr70
    integer(c_int) :: ikr72
    integer(c_int) :: isr74
    integer(c_int) :: isr76
    integer(c_int) :: izr77
    integer(c_int) :: izr80
    integer(c_int) :: imo82
    integer(c_int) :: imo84
    integer(c_int) :: iru88
    integer(c_int) :: ipd92
    integer(c_int) :: isr75
    integer(c_int) :: iru86
    integer(c_int) :: iru87
    integer(c_int) :: ipd89
    integer(c_int) :: ipd91
    integer(c_int) :: icd93
    integer(c_int) :: icd96
    integer(c_int) :: isn98
    integer(c_int) :: isn100
    integer(c_int) :: isn102
    integer(c_int) :: isn104
    integer(c_int) :: ineut
    integer(c_int) :: iprot
  end type c_Chem_Ids

  contains    

  !------------------------------------------------------------------------------
  !  Subroutines
  !------------------------------------------------------------------------------

  !------------------------------------------------------------------------------
  !  Subroutine: c_set_some_isos
  !  This subroutine sets the values of the c_Chem_Ids type to the values of the
  !  corresponding Chem_Ids type in mesa/chem/chem_def.f90
  !------------------------------------------------------------------------------
  subroutine c_set_some_isos(cip)
    use chem_def, only: get_nuclide_index

    implicit none
    type(c_Chem_Ids), pointer :: cip

    cip%ih1 = get_nuclide_index('h1')
    cip%ih2 = get_nuclide_index('h2')
    cip%ih3 = get_nuclide_index('h3')
    cip%ihe3 = get_nuclide_index('he3')
    cip%ihe4 = get_nuclide_index('he4')
    cip%ili6 = get_nuclide_index('li6')
    cip%ili7 = get_nuclide_index('li7')
    cip%ili8 = get_nuclide_index('li8')
    cip%ibe7 = get_nuclide_index('be7')
    cip%ibe8 = get_nuclide_index('be8')
    cip%ibe9 = get_nuclide_index('be9')
    cip%ibe10 = get_nuclide_index('be10')
    cip%ibe11 = get_nuclide_index('be11')
    cip%ib8 = get_nuclide_index('b8')
    cip%ib10 = get_nuclide_index('b10')
    cip%ib11 = get_nuclide_index('b11')
    cip%ib12 = get_nuclide_index('b12')
    cip%ib13 = get_nuclide_index('b13')
    cip%ib14 = get_nuclide_index('b14')
    cip%ic9 = get_nuclide_index('c9')
    cip%ic10 = get_nuclide_index('c10')
    cip%ic11 = get_nuclide_index('c11')
    cip%ic12 = get_nuclide_index('c12')
    cip%ic13 = get_nuclide_index('c13')
    cip%ic14 = get_nuclide_index('c14')
    cip%ic15 = get_nuclide_index('c15')
    cip%ic16 = get_nuclide_index('c16')
    cip%in12 = get_nuclide_index('n12')
    cip%in13 = get_nuclide_index('n13')
    cip%in14 = get_nuclide_index('n14')
    cip%in15 = get_nuclide_index('n15')
    cip%in16 = get_nuclide_index('n16')
    cip%in17 = get_nuclide_index('n17')
    cip%in18 = get_nuclide_index('n18')
    cip%in19 = get_nuclide_index('n19')
    cip%in20 = get_nuclide_index('n20')
    cip%io13 = get_nuclide_index('o13')
    cip%io14 = get_nuclide_index('o14')
    cip%io15 = get_nuclide_index('o15')
    cip%io16 = get_nuclide_index('o16')
    cip%io17 = get_nuclide_index('o17')
    cip%io18 = get_nuclide_index('o18')
    cip%io19 = get_nuclide_index('o19')
    cip%io20 = get_nuclide_index('o20')
    cip%if15 = get_nuclide_index('f15')
    cip%if16 = get_nuclide_index('f16')
    cip%if17 = get_nuclide_index('f17')
    cip%if18 = get_nuclide_index('f18')
    cip%if19 = get_nuclide_index('f19')
    cip%if20 = get_nuclide_index('f20')
    cip%if21 = get_nuclide_index('f21')
    cip%if22 = get_nuclide_index('f22')
    cip%if23 = get_nuclide_index('f23')
    cip%if24 = get_nuclide_index('f24')
    cip%ine17 = get_nuclide_index('ne17')
    cip%ine18 = get_nuclide_index('ne18')
    cip%ine19 = get_nuclide_index('ne19')
    cip%ine20 = get_nuclide_index('ne20')
    cip%ine21 = get_nuclide_index('ne21')
    cip%ine22 = get_nuclide_index('ne22')
    cip%ine23 = get_nuclide_index('ne23')
    cip%ine24 = get_nuclide_index('ne24')
    cip%ine25 = get_nuclide_index('ne25')
    cip%ine26 = get_nuclide_index('ne26')
    cip%ine27 = get_nuclide_index('ne27')
    cip%ine28 = get_nuclide_index('ne28')
    cip%ina20 = get_nuclide_index('na20')
    cip%ina21 = get_nuclide_index('na21')
    cip%ina22 = get_nuclide_index('na22')
    cip%ina23 = get_nuclide_index('na23')
    cip%ina24 = get_nuclide_index('na24')
    cip%ina25 = get_nuclide_index('na25')
    cip%ina26 = get_nuclide_index('na26')
    cip%ina27 = get_nuclide_index('na27')
    cip%ina28 = get_nuclide_index('na28')
    cip%ina29 = get_nuclide_index('na29')
    cip%ina30 = get_nuclide_index('na30')
    cip%ina31 = get_nuclide_index('na31')
    cip%img20 = get_nuclide_index('mg20')
    cip%img21 = get_nuclide_index('mg21')
    cip%img22 = get_nuclide_index('mg22')
    cip%img23 = get_nuclide_index('mg23')
    cip%img24 = get_nuclide_index('mg24')
    cip%img25 = get_nuclide_index('mg25')
    cip%img26 = get_nuclide_index('mg26')
    cip%img27 = get_nuclide_index('mg27')
    cip%img28 = get_nuclide_index('mg28')
    cip%img29 = get_nuclide_index('mg29')
    cip%img30 = get_nuclide_index('mg30')
    cip%img31 = get_nuclide_index('mg31')
    cip%img32 = get_nuclide_index('mg32')
    cip%img33 = get_nuclide_index('mg33')
    cip%ial22 = get_nuclide_index('al22')
    cip%ial23 = get_nuclide_index('al23')
    cip%ial24 = get_nuclide_index('al24')
    cip%ial25 = get_nuclide_index('al25')
    cip%ial26 = get_nuclide_index('al26')
    cip%ial27 = get_nuclide_index('al27')
    cip%ial28 = get_nuclide_index('al28')
    cip%ial29 = get_nuclide_index('al29')
    cip%ial30 = get_nuclide_index('al30')
    cip%ial31 = get_nuclide_index('al31')
    cip%ial32 = get_nuclide_index('al32')
    cip%ial33 = get_nuclide_index('al33')
    cip%ial34 = get_nuclide_index('al34')
    cip%ial35 = get_nuclide_index('al35')
    cip%isi22 = get_nuclide_index('si22')
    cip%isi23 = get_nuclide_index('si23')
    cip%isi24 = get_nuclide_index('si24')
    cip%isi25 = get_nuclide_index('si25')
    cip%isi26 = get_nuclide_index('si26')
    cip%isi27 = get_nuclide_index('si27')
    cip%isi28 = get_nuclide_index('si28')
    cip%isi29 = get_nuclide_index('si29')
    cip%isi30 = get_nuclide_index('si30')
    cip%isi31 = get_nuclide_index('si31')
    cip%isi32 = get_nuclide_index('si32')
    cip%isi33 = get_nuclide_index('si33')
    cip%isi34 = get_nuclide_index('si34')
    cip%isi35 = get_nuclide_index('si35')
    cip%isi36 = get_nuclide_index('si36')
    cip%isi37 = get_nuclide_index('si37')
    cip%isi38 = get_nuclide_index('si38')
    cip%ip26 = get_nuclide_index('p26')
    cip%ip27 = get_nuclide_index('p27')
    cip%ip28 = get_nuclide_index('p28')
    cip%ip29 = get_nuclide_index('p29')
    cip%ip30 = get_nuclide_index('p30')
    cip%ip31 = get_nuclide_index('p31')
    cip%ip32 = get_nuclide_index('p32')
    cip%ip33 = get_nuclide_index('p33')
    cip%ip34 = get_nuclide_index('p34')
    cip%ip35 = get_nuclide_index('p35')
    cip%ip36 = get_nuclide_index('p36')
    cip%ip37 = get_nuclide_index('p37')
    cip%ip38 = get_nuclide_index('p38')
    cip%ip39 = get_nuclide_index('p39')
    cip%ip40 = get_nuclide_index('p40')
    cip%is27 = get_nuclide_index('s27')
    cip%is28 = get_nuclide_index('s28')
    cip%is29 = get_nuclide_index('s29')
    cip%is30 = get_nuclide_index('s30')
    cip%is31 = get_nuclide_index('s31')
    cip%is32 = get_nuclide_index('s32')
    cip%is33 = get_nuclide_index('s33')
    cip%is34 = get_nuclide_index('s34')
    cip%is35 = get_nuclide_index('s35')
    cip%is36 = get_nuclide_index('s36')
    cip%is37 = get_nuclide_index('s37')
    cip%is38 = get_nuclide_index('s38')
    cip%is39 = get_nuclide_index('s39')
    cip%is40 = get_nuclide_index('s40')
    cip%is41 = get_nuclide_index('s41')
    cip%is42 = get_nuclide_index('s42')
    cip%icl31 = get_nuclide_index('cl31')
    cip%icl32 = get_nuclide_index('cl32')
    cip%icl33 = get_nuclide_index('cl33')
    cip%icl34 = get_nuclide_index('cl34')
    cip%icl35 = get_nuclide_index('cl35')
    cip%icl36 = get_nuclide_index('cl36')
    cip%icl37 = get_nuclide_index('cl37')
    cip%icl38 = get_nuclide_index('cl38')
    cip%icl39 = get_nuclide_index('cl39')
    cip%icl40 = get_nuclide_index('cl40')
    cip%icl41 = get_nuclide_index('cl41')
    cip%icl42 = get_nuclide_index('cl42')
    cip%icl43 = get_nuclide_index('cl43')
    cip%icl44 = get_nuclide_index('cl44')
    cip%iar31 = get_nuclide_index('ar31')
    cip%iar32 = get_nuclide_index('ar32')
    cip%iar33 = get_nuclide_index('ar33')
    cip%iar34 = get_nuclide_index('ar34')
    cip%iar35 = get_nuclide_index('ar35')
    cip%iar36 = get_nuclide_index('ar36')
    cip%iar37 = get_nuclide_index('ar37')
    cip%iar38 = get_nuclide_index('ar38')
    cip%iar39 = get_nuclide_index('ar39')
    cip%iar40 = get_nuclide_index('ar40')
    cip%iar41 = get_nuclide_index('ar41')
    cip%iar42 = get_nuclide_index('ar42')
    cip%iar43 = get_nuclide_index('ar43')
    cip%iar44 = get_nuclide_index('ar44')
    cip%iar45 = get_nuclide_index('ar45')
    cip%iar46 = get_nuclide_index('ar46')
    cip%iar47 = get_nuclide_index('ar47')
    cip%ik35 = get_nuclide_index('k35')
    cip%ik36 = get_nuclide_index('k36')
    cip%ik37 = get_nuclide_index('k37')
    cip%ik38 = get_nuclide_index('k38')
    cip%ik39 = get_nuclide_index('k39')
    cip%ik40 = get_nuclide_index('k40')
    cip%ik41 = get_nuclide_index('k41')
    cip%ik42 = get_nuclide_index('k42')
    cip%ik43 = get_nuclide_index('k43')
    cip%ik44 = get_nuclide_index('k44')
    cip%ik45 = get_nuclide_index('k45')
    cip%ik46 = get_nuclide_index('k46')
    cip%ik47 = get_nuclide_index('k47')
    cip%ica35 = get_nuclide_index('ca35')
    cip%ica36 = get_nuclide_index('ca36')
    cip%ica37 = get_nuclide_index('ca37')
    cip%ica38 = get_nuclide_index('ca38')
    cip%ica39 = get_nuclide_index('ca39')
    cip%ica40 = get_nuclide_index('ca40')
    cip%ica41 = get_nuclide_index('ca41')
    cip%ica42 = get_nuclide_index('ca42')
    cip%ica43 = get_nuclide_index('ca43')
    cip%ica44 = get_nuclide_index('ca44')
    cip%ica45 = get_nuclide_index('ca45')
    cip%ica46 = get_nuclide_index('ca46')
    cip%ica47 = get_nuclide_index('ca47')
    cip%ica48 = get_nuclide_index('ca48')
    cip%ica49 = get_nuclide_index('ca49')
    cip%ica50 = get_nuclide_index('ca50')
    cip%ica51 = get_nuclide_index('ca51')
    cip%ica52 = get_nuclide_index('ca52')
    cip%ica53 = get_nuclide_index('ca53')
    cip%isc40 = get_nuclide_index('sc40')
    cip%isc41 = get_nuclide_index('sc41')
    cip%isc42 = get_nuclide_index('sc42')
    cip%isc43 = get_nuclide_index('sc43')
    cip%isc44 = get_nuclide_index('sc44')
    cip%isc45 = get_nuclide_index('sc45')
    cip%isc46 = get_nuclide_index('sc46')
    cip%isc47 = get_nuclide_index('sc47')
    cip%isc48 = get_nuclide_index('sc48')
    cip%isc49 = get_nuclide_index('sc49')
    cip%isc50 = get_nuclide_index('sc50')
    cip%isc51 = get_nuclide_index('sc51')
    cip%isc52 = get_nuclide_index('sc52')
    cip%isc53 = get_nuclide_index('sc53')
    cip%iti39 = get_nuclide_index('ti39')
    cip%iti40 = get_nuclide_index('ti40')
    cip%iti41 = get_nuclide_index('ti41')
    cip%iti42 = get_nuclide_index('ti42')
    cip%iti43 = get_nuclide_index('ti43')
    cip%iti44 = get_nuclide_index('ti44')
    cip%iti45 = get_nuclide_index('ti45')
    cip%iti46 = get_nuclide_index('ti46')
    cip%iti47 = get_nuclide_index('ti47')
    cip%iti48 = get_nuclide_index('ti48')
    cip%iti49 = get_nuclide_index('ti49')
    cip%iti50 = get_nuclide_index('ti50')
    cip%iti51 = get_nuclide_index('ti51')
    cip%iti52 = get_nuclide_index('ti52')
    cip%iti53 = get_nuclide_index('ti53')
    cip%iti54 = get_nuclide_index('ti54')
    cip%iti55 = get_nuclide_index('ti55')
    cip%iv43 = get_nuclide_index('v43')
    cip%iv44 = get_nuclide_index('v44')
    cip%iv45 = get_nuclide_index('v45')
    cip%iv46 = get_nuclide_index('v46')
    cip%iv47 = get_nuclide_index('v47')
    cip%iv48 = get_nuclide_index('v48')
    cip%iv49 = get_nuclide_index('v49')
    cip%iv50 = get_nuclide_index('v50')
    cip%iv51 = get_nuclide_index('v51')
    cip%iv52 = get_nuclide_index('v52')
    cip%iv53 = get_nuclide_index('v53')
    cip%iv54 = get_nuclide_index('v54')
    cip%iv55 = get_nuclide_index('v55')
    cip%iv56 = get_nuclide_index('v56')
    cip%iv57 = get_nuclide_index('v57')
    cip%icr43 = get_nuclide_index('cr43')
    cip%icr44 = get_nuclide_index('cr44')
    cip%icr45 = get_nuclide_index('cr45')
    cip%icr46 = get_nuclide_index('cr46')
    cip%icr47 = get_nuclide_index('cr47')
    cip%icr48 = get_nuclide_index('cr48')
    cip%icr49 = get_nuclide_index('cr49')
    cip%icr50 = get_nuclide_index('cr50')
    cip%icr51 = get_nuclide_index('cr51')
    cip%icr52 = get_nuclide_index('cr52')
    cip%icr53 = get_nuclide_index('cr53')
    cip%icr54 = get_nuclide_index('cr54')
    cip%icr55 = get_nuclide_index('cr55')
    cip%icr56 = get_nuclide_index('cr56')
    cip%icr57 = get_nuclide_index('cr57')
    cip%icr58 = get_nuclide_index('cr58')
    cip%icr59 = get_nuclide_index('cr59')
    cip%icr60 = get_nuclide_index('cr60')
    cip%icr61 = get_nuclide_index('cr61')
    cip%icr62 = get_nuclide_index('cr62')
    cip%icr63 = get_nuclide_index('cr63')
    cip%icr64 = get_nuclide_index('cr64')
    cip%icr65 = get_nuclide_index('cr65')
    cip%icr66 = get_nuclide_index('cr66')
    cip%imn46 = get_nuclide_index('mn46')
    cip%imn47 = get_nuclide_index('mn47')
    cip%imn48 = get_nuclide_index('mn48')
    cip%imn49 = get_nuclide_index('mn49')
    cip%imn50 = get_nuclide_index('mn50')
    cip%imn51 = get_nuclide_index('mn51')
    cip%imn52 = get_nuclide_index('mn52')
    cip%imn53 = get_nuclide_index('mn53')
    cip%imn54 = get_nuclide_index('mn54')
    cip%imn55 = get_nuclide_index('mn55')
    cip%imn56 = get_nuclide_index('mn56')
    cip%imn57 = get_nuclide_index('mn57')
    cip%imn58 = get_nuclide_index('mn58')
    cip%imn59 = get_nuclide_index('mn59')
    cip%imn60 = get_nuclide_index('mn60')
    cip%imn61 = get_nuclide_index('mn61')
    cip%imn62 = get_nuclide_index('mn62')
    cip%imn63 = get_nuclide_index('mn63')
    cip%ife46 = get_nuclide_index('fe46')
    cip%ife47 = get_nuclide_index('fe47')
    cip%ife48 = get_nuclide_index('fe48')
    cip%ife49 = get_nuclide_index('fe49')
    cip%ife50 = get_nuclide_index('fe50')
    cip%ife51 = get_nuclide_index('fe51')
    cip%ife52 = get_nuclide_index('fe52')
    cip%ife53 = get_nuclide_index('fe53')
    cip%ife54 = get_nuclide_index('fe54')
    cip%ife55 = get_nuclide_index('fe55')
    cip%ife56 = get_nuclide_index('fe56')
    cip%ife57 = get_nuclide_index('fe57')
    cip%ife58 = get_nuclide_index('fe58')
    cip%ife59 = get_nuclide_index('fe59')
    cip%ife60 = get_nuclide_index('fe60')
    cip%ife61 = get_nuclide_index('fe61')
    cip%ife62 = get_nuclide_index('fe62')
    cip%ife63 = get_nuclide_index('fe63')
    cip%ife64 = get_nuclide_index('fe64')
    cip%ife65 = get_nuclide_index('fe65')
    cip%ife66 = get_nuclide_index('fe66')
    cip%ife68 = get_nuclide_index('fe68')
    cip%ico50 = get_nuclide_index('co50')
    cip%ico51 = get_nuclide_index('co51')
    cip%ico52 = get_nuclide_index('co52')
    cip%ico53 = get_nuclide_index('co53')
    cip%ico54 = get_nuclide_index('co54')
    cip%ico55 = get_nuclide_index('co55')
    cip%ico56 = get_nuclide_index('co56')
    cip%ico57 = get_nuclide_index('co57')
    cip%ico58 = get_nuclide_index('co58')
    cip%ico59 = get_nuclide_index('co59')
    cip%ico60 = get_nuclide_index('co60')
    cip%ico61 = get_nuclide_index('co61')
    cip%ico62 = get_nuclide_index('co62')
    cip%ico63 = get_nuclide_index('co63')
    cip%ico64 = get_nuclide_index('co64')
    cip%ico65 = get_nuclide_index('co65')
    cip%ico66 = get_nuclide_index('co66')
    cip%ico67 = get_nuclide_index('co67')
    cip%ini50 = get_nuclide_index('ni50')
    cip%ini51 = get_nuclide_index('ni51')
    cip%ini52 = get_nuclide_index('ni52')
    cip%ini53 = get_nuclide_index('ni53')
    cip%ini54 = get_nuclide_index('ni54')
    cip%ini55 = get_nuclide_index('ni55')
    cip%ini56 = get_nuclide_index('ni56')
    cip%ini57 = get_nuclide_index('ni57')
    cip%ini58 = get_nuclide_index('ni58')
    cip%ini59 = get_nuclide_index('ni59')
    cip%ini60 = get_nuclide_index('ni60')
    cip%ini61 = get_nuclide_index('ni61')
    cip%ini62 = get_nuclide_index('ni62')
    cip%ini63 = get_nuclide_index('ni63')
    cip%ini64 = get_nuclide_index('ni64')
    cip%ini65 = get_nuclide_index('ni65')
    cip%ini66 = get_nuclide_index('ni66')
    cip%ini67 = get_nuclide_index('ni67')
    cip%ini68 = get_nuclide_index('ni68')
    cip%ini69 = get_nuclide_index('ni69')
    cip%ini70 = get_nuclide_index('ni70')
    cip%ini71 = get_nuclide_index('ni71')
    cip%ini72 = get_nuclide_index('ni72')
    cip%ini73 = get_nuclide_index('ni73')
    cip%icu56 = get_nuclide_index('cu56')
    cip%icu57 = get_nuclide_index('cu57')
    cip%icu58 = get_nuclide_index('cu58')
    cip%icu59 = get_nuclide_index('cu59')
    cip%icu60 = get_nuclide_index('cu60')
    cip%icu61 = get_nuclide_index('cu61')
    cip%icu62 = get_nuclide_index('cu62')
    cip%icu63 = get_nuclide_index('cu63')
    cip%icu64 = get_nuclide_index('cu64')
    cip%icu65 = get_nuclide_index('cu65')
    cip%icu66 = get_nuclide_index('cu66')
    cip%icu67 = get_nuclide_index('cu67')
    cip%icu68 = get_nuclide_index('cu68')
    cip%icu69 = get_nuclide_index('cu69')
    cip%icu70 = get_nuclide_index('cu70')
    cip%icu71 = get_nuclide_index('cu71')
    cip%icu72 = get_nuclide_index('cu72')
    cip%izn55 = get_nuclide_index('zn55')
    cip%izn56 = get_nuclide_index('zn56')
    cip%izn57 = get_nuclide_index('zn57')
    cip%izn58 = get_nuclide_index('zn58')
    cip%izn59 = get_nuclide_index('zn59')
    cip%izn60 = get_nuclide_index('zn60')
    cip%izn61 = get_nuclide_index('zn61')
    cip%izn62 = get_nuclide_index('zn62')
    cip%izn63 = get_nuclide_index('zn63')
    cip%izn64 = get_nuclide_index('zn64')
    cip%izn65 = get_nuclide_index('zn65')
    cip%izn66 = get_nuclide_index('zn66')
    cip%izn67 = get_nuclide_index('zn67')
    cip%izn68 = get_nuclide_index('zn68')
    cip%izn69 = get_nuclide_index('zn69')
    cip%izn70 = get_nuclide_index('zn70')
    cip%izn71 = get_nuclide_index('zn71')
    cip%izn72 = get_nuclide_index('zn72')
    cip%izn73 = get_nuclide_index('zn73')
    cip%izn74 = get_nuclide_index('zn74')
    cip%iga60 = get_nuclide_index('ga60')
    cip%iga61 = get_nuclide_index('ga61')
    cip%iga62 = get_nuclide_index('ga62')
    cip%iga63 = get_nuclide_index('ga63')
    cip%iga64 = get_nuclide_index('ga64')
    cip%iga65 = get_nuclide_index('ga65')
    cip%iga66 = get_nuclide_index('ga66')
    cip%iga67 = get_nuclide_index('ga67')
    cip%iga68 = get_nuclide_index('ga68')
    cip%iga69 = get_nuclide_index('ga69')
    cip%iga70 = get_nuclide_index('ga70')
    cip%iga71 = get_nuclide_index('ga71')
    cip%iga72 = get_nuclide_index('ga72')
    cip%iga73 = get_nuclide_index('ga73')
    cip%iga74 = get_nuclide_index('ga74')
    cip%iga75 = get_nuclide_index('ga75')
    cip%ige59 = get_nuclide_index('ge59')
    cip%ige60 = get_nuclide_index('ge60')
    cip%ige61 = get_nuclide_index('ge61')
    cip%ige62 = get_nuclide_index('ge62')
    cip%ige63 = get_nuclide_index('ge63')
    cip%ige64 = get_nuclide_index('ge64')
    cip%ige65 = get_nuclide_index('ge65')
    cip%ige66 = get_nuclide_index('ge66')
    cip%ige67 = get_nuclide_index('ge67')
    cip%ige68 = get_nuclide_index('ge68')
    cip%ige69 = get_nuclide_index('ge69')
    cip%ige70 = get_nuclide_index('ge70')
    cip%ige71 = get_nuclide_index('ge71')
    cip%ige72 = get_nuclide_index('ge72')
    cip%ige73 = get_nuclide_index('ge73')
    cip%ige74 = get_nuclide_index('ge74')
    cip%ige75 = get_nuclide_index('ge75')
    cip%ige76 = get_nuclide_index('ge76')
    cip%ias71 = get_nuclide_index('as71')
    cip%ias72 = get_nuclide_index('as72')
    cip%ias73 = get_nuclide_index('as73')
    cip%ias74 = get_nuclide_index('as74')
    cip%ias75 = get_nuclide_index('as75')
    cip%ias76 = get_nuclide_index('as76')
    cip%ias77 = get_nuclide_index('as77')
    cip%ias78 = get_nuclide_index('as78')
    cip%ias79 = get_nuclide_index('as79')
    cip%ise68 = get_nuclide_index('se68')
    cip%ise69 = get_nuclide_index('se69')
    cip%ise70 = get_nuclide_index('se70')
    cip%ise71 = get_nuclide_index('se71')
    cip%ise72 = get_nuclide_index('se72')
    cip%ise73 = get_nuclide_index('se73')
    cip%ise74 = get_nuclide_index('se74')
    cip%ise75 = get_nuclide_index('se75')
    cip%ise76 = get_nuclide_index('se76')
    cip%ikr70 = get_nuclide_index('kr70')
    cip%ikr72 = get_nuclide_index('kr72')
    cip%isr74 = get_nuclide_index('sr74')
    cip%isr76 = get_nuclide_index('sr76')
    cip%izr77 = get_nuclide_index('zr77')
    cip%izr80 = get_nuclide_index('zr80')
    cip%imo82 = get_nuclide_index('mo82')
    cip%imo84 = get_nuclide_index('mo84')
    cip%iru88 = get_nuclide_index('ru88')
    cip%ipd92 = get_nuclide_index('pd92')
    cip%isr75 = get_nuclide_index('sr75')
    cip%iru86 = get_nuclide_index('ru86')
    cip%iru87 = get_nuclide_index('ru87')
    cip%ipd89 = get_nuclide_index('pd89')
    cip%ipd91 = get_nuclide_index('pd91')
    cip%icd93 = get_nuclide_index('cd93')
    cip%icd96 = get_nuclide_index('cd96')
    cip%isn98 = get_nuclide_index('sn98')
    cip%isn100 = get_nuclide_index('sn100')
    cip%isn102 = get_nuclide_index('sn102')
    cip%isn104 = get_nuclide_index('sn104')
    cip%ineut = get_nuclide_index('neut')
    cip%iprot = get_nuclide_index('prot')
  end subroutine c_set_some_isos

end module chem_interface_def
